"""create_report_models

Revision ID: 084bc5e7e4a5
Revises: 2359e3924a40
Create Date: 2026-05-21 10:43:25.160001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '084bc5e7e4a5'
down_revision: Union[str, None] = '2359e3924a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_schedules_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_organization_id'), ['organization_id'], unique=False)

    op.create_table('report_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_schedule_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_schedule_id'], ['report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_histories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_histories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_histories_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_histories_report_schedule_id'), ['report_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_histories_report_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_report_histories_organization_id'))
        batch_op.drop_index(batch_op.f('ix_report_histories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_report_histories_id'))

    op.drop_table('report_histories')
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_schedules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_id'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_dashboard_id'))

    op.drop_table('report_schedules')
    # ### end Alembic commands ###
