"""create_alert_models

Revision ID: 2359e3924a40
Revises: 28c6e6690296
Create Date: 2026-05-21 07:09:53.960631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2359e3924a40'
down_revision: Union[str, None] = '28c6e6690296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('time_window_minutes', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snooze_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('slack_webhook', sa.String(length=500), nullable=True),
    sa.Column('email_recipient', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('alert_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_histories_alert_rule_id'), ['alert_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_histories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_histories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_histories_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_histories_organization_id'))
        batch_op.drop_index(batch_op.f('ix_alert_histories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_alert_histories_id'))
        batch_op.drop_index(batch_op.f('ix_alert_histories_alert_rule_id'))

    op.drop_table('alert_histories')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_id'))

    op.drop_table('alert_rules')
    # ### end Alembic commands ###

