"""create_dashboard_and_widget_models

Revision ID: 28c6e6690296
Revises: ed2acb3e5e28
Create Date: 2026-05-21 06:55:50.100319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28c6e6690296'
down_revision: Union[str, None] = 'ed2acb3e5e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_share_token'), ['share_token'], unique=True)

    op.create_table('widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widgets_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widgets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widgets_is_deleted'), ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widgets_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_widgets_id'))
        batch_op.drop_index(batch_op.f('ix_widgets_dashboard_id'))

    op.drop_table('widgets')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_share_token'))
        batch_op.drop_index(batch_op.f('ix_dashboards_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dashboards_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_dashboards_id'))

    op.drop_table('dashboards')
    # ### end Alembic commands ###

